from __future__ import annotations

# ============================================================
# Standard library imports
# 标准库导入
# ============================================================
import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

# ============================================================
# Make project root importable
# 把项目根目录加入导入路径
# ============================================================
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# ============================================================
# Local imports
# 本地导入
# ============================================================
from src.data_factory.export.export_stage2_manifest import (
    export_stage2_manifest_jsonl,
)
from src.data_factory.schemas import ExportItem


# ============================================================
# Basic helpers
# 基础工具函数
# ============================================================
def str2bool(x: str | bool) -> bool:
    """
    EN:
    Convert common string values to bool.

    ZH:
    将常见字符串形式转换为 bool。
    """
    if isinstance(x, bool):
        return x

    s = str(x).strip().lower()

    if s in {"1", "true", "yes", "y", "on"}:
        return True

    if s in {"0", "false", "no", "n", "off"}:
        return False

    raise argparse.ArgumentTypeError(f"Cannot parse boolean value from: {x}")


def parse_args() -> argparse.Namespace:
    """
    EN:
    Parse CLI arguments.

    ZH:
    解析命令行参数。
    """
    parser = argparse.ArgumentParser(
        description=(
            "Export a few-shot Stage2 manifest from data-factory manifest.jsonl "
            "or manifest.corrected.jsonl. Supports self / speaker_pool / "
            "fixed_reference prompt selection."
        )
    )

    # --------------------------------------------------------
    # Input / output
    # 输入输出
    # --------------------------------------------------------
    parser.add_argument(
        "--manifest_jsonl",
        type=str,
        required=True,
        help=(
            "Input manifest.jsonl / manifest.corrected.jsonl generated by "
            "Resonastra data factory."
        ),
    )
    parser.add_argument(
        "--output_stage2_manifest",
        type=str,
        required=True,
        help="Output stage2_manifest.fewshot.jsonl path.",
    )
    parser.add_argument(
        "--prompt_selection_report_path",
        type=str,
        default=None,
        help=(
            "Output prompt selection report JSON. If omitted, it will be saved "
            "beside output_stage2_manifest as prompt_selection_report.json."
        ),
    )

    # --------------------------------------------------------
    # Prompt mode
    # prompt 模式
    # --------------------------------------------------------
    parser.add_argument(
        "--prompt_mode",
        type=str,
        default="speaker_pool",
        choices=[
            "self",
            "speaker_pool",
            "fixed_reference",
        ],
        help=(
            "Prompt selection mode. "
            "self: prompt_wav_path = target_wav_path. "
            "speaker_pool: use self when valid, otherwise select a same-speaker "
            "prompt candidate. "
            "fixed_reference: use one fixed prompt wav for all samples."
        ),
    )
    parser.add_argument(
        "--fixed_prompt_wav_path",
        type=str,
        default=None,
        help=(
            "Required when prompt_mode=fixed_reference. "
            "This wav will be used as prompt_wav_path for all target samples."
        ),
    )

    # --------------------------------------------------------
    # Prompt duration policy
    # prompt 时长策略
    # --------------------------------------------------------
    parser.add_argument(
        "--min_prompt_sec",
        type=float,
        default=3.0,
        help="Minimum allowed prompt duration in seconds.",
    )
    parser.add_argument(
        "--max_prompt_sec",
        type=float,
        default=10.0,
        help="Maximum allowed prompt duration in seconds.",
    )
    parser.add_argument(
        "--prefer_prompt_sec",
        type=float,
        default=6.0,
        help=(
            "Preferred prompt duration. In speaker_pool mode, candidates closer "
            "to this duration are preferred."
        ),
    )
    parser.add_argument(
        "--allow_self_prompt",
        type=str2bool,
        default=True,
        help=(
            "Only used in speaker_pool mode. If true and target clip duration "
            "is valid, use the target clip itself as prompt."
        ),
    )
    parser.add_argument(
        "--strict_prompt_duration",
        type=str2bool,
        default=True,
        help=(
            "If true, fixed_reference prompt duration outside "
            "[min_prompt_sec, max_prompt_sec] raises an error."
        ),
    )

    # --------------------------------------------------------
    # Manifest row fallback values
    # manifest 行字段兜底
    # --------------------------------------------------------
    parser.add_argument(
        "--default_speaker_name",
        type=str,
        default="default_speaker",
        help=(
            "Fallback speaker_name when a manifest row does not contain "
            "speaker_name. For few-shot v1, this usually means all samples "
            "belong to the same user speaker."
        ),
    )
    parser.add_argument(
        "--default_language",
        type=str,
        default="zh",
        help="Fallback language when a manifest row does not contain language.",
    )
    parser.add_argument(
        "--default_asr_source",
        type=str,
        default="fewshot_manifest",
        help="Fallback asr_source when a manifest row does not contain asr_source.",
    )
    parser.add_argument(
        "--default_text_status",
        type=str,
        default="manual_corrected",
        help=(
            "Fallback text_status when a manifest row does not contain "
            "text_status. corrected manifest usually means manual_corrected."
        ),
    )

    # --------------------------------------------------------
    # Invalid row policy
    # 无效行处理策略
    # --------------------------------------------------------
    parser.add_argument(
        "--skip_invalid_rows",
        type=str2bool,
        default=False,
        help=(
            "If true, rows with missing wav_path or empty text are skipped and "
            "reported. If false, invalid rows raise an error."
        ),
    )
    parser.add_argument(
        "--allow_empty_text",
        type=str2bool,
        default=False,
        help=(
            "If true, rows with empty text are allowed. Not recommended for "
            "few-shot training."
        ),
    )

    # --------------------------------------------------------
    # Logging
    # 日志
    # --------------------------------------------------------
    parser.add_argument(
        "--conversion_report_path",
        type=str,
        default=None,
        help=(
            "Optional JSON report for manifest-row-to-ExportItem conversion. "
            "If omitted, saved beside output_stage2_manifest as "
            "fewshot_manifest_conversion_report.json."
        ),
    )
    parser.add_argument(
        "--print_records_preview",
        type=str2bool,
        default=True,
        help="Print a short preview of exported records.",
    )
    parser.add_argument(
        "--max_preview_records",
        type=int,
        default=5,
        help="Maximum records to preview in stdout.",
    )

    return parser.parse_args()


def read_jsonl(path: str | Path) -> list[dict[str, Any]]:
    """
    EN:
    Read JSONL file into a list of dicts.

    ZH:
    读取 JSONL 文件为 dict 列表。
    """
    p = Path(path).resolve()

    if not p.exists():
        raise FileNotFoundError(f"manifest_jsonl not found: {p}")

    if not p.is_file():
        raise ValueError(f"manifest_jsonl is not a file: {p}")

    rows: list[dict[str, Any]] = []

    with p.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            s = line.strip()

            if not s:
                continue

            try:
                obj = json.loads(s)
            except Exception as e:
                raise ValueError(
                    f"Invalid JSON at {p}:{line_no}: {s[:200]}"
                ) from e

            if not isinstance(obj, dict):
                raise ValueError(
                    f"Expected JSON object at {p}:{line_no}, got {type(obj)}"
                )

            rows.append(obj)

    if not rows:
        raise ValueError(f"No valid JSONL rows found in: {p}")

    return rows


def save_json(obj: dict[str, Any], path: str | Path) -> None:
    """
    EN:
    Save JSON object.

    ZH:
    保存 JSON 对象。
    """
    p = Path(path).resolve()
    p.parent.mkdir(parents=True, exist_ok=True)

    with p.open("w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def safe_float(x: Any, default: float = math.nan) -> float:
    """
    EN:
    Defensive float conversion.

    ZH:
    防御式 float 转换。
    """
    try:
        if x is None:
            return float(default)
        return float(x)
    except Exception:
        return float(default)


def is_finite_number(x: float) -> bool:
    """
    EN:
    Check finite number.

    ZH:
    检查是否是有限数值。
    """
    try:
        return math.isfinite(float(x))
    except Exception:
        return False


def normalize_text(x: Any) -> str:
    """
    EN:
    Normalize text-like value.

    ZH:
    规范文本值。
    """
    if x is None:
        return ""
    return str(x).strip()


def normalize_path(path: Any, base_dir: str | Path | None = None) -> str:
    """
    EN:
    Normalize a path. Relative path is resolved against base_dir if provided.

    ZH:
    规范化路径。若是相对路径且提供 base_dir，则基于 base_dir 解析。
    """
    if path is None:
        return ""

    s = str(path).strip()

    if not s:
        return ""

    p = Path(s)

    if not p.is_absolute() and base_dir is not None:
        p = Path(base_dir).resolve() / p

    return str(p.resolve())


def resolve_default_report_path(
    output_stage2_manifest: str | Path,
    filename: str,
) -> str:
    """
    EN:
    Build a default report path beside output_stage2_manifest.

    ZH:
    在 output_stage2_manifest 同级目录下生成默认报告路径。
    """
    out = Path(output_stage2_manifest).resolve()
    return str(out.with_name(filename))


def row_to_export_item(
    row: dict[str, Any],
    *,
    row_index: int,
    manifest_dir: Path,
    default_speaker_name: str,
    default_language: str,
    default_asr_source: str,
    default_text_status: str,
    allow_empty_text: bool,
) -> tuple[ExportItem | None, dict[str, Any]]:
    """
    EN:
    Convert one manifest row into ExportItem.

    Supported input rows:
    - data-factory manifest rows:
        sample_id, wav_path, text, language, speaker_name, duration_sec, ...

    - corrected manifest rows:
        same as above, often text_status=manual_corrected.

    ZH:
    将一条 manifest 行转换为 ExportItem。

    支持：
    - 数据工厂 manifest 行
    - corrected manifest 行
    """
    wav_path = normalize_path(
        row.get("wav_path", row.get("target_wav_path", "")),
        base_dir=manifest_dir,
    )

    sample_id = normalize_text(row.get("sample_id", ""))

    if not sample_id and wav_path:
        sample_id = Path(wav_path).stem

    if not sample_id:
        sample_id = f"row_{row_index:06d}"

    text = normalize_text(
        row.get(
            "text",
            row.get(
                "raw_text",
                row.get("norm_text", ""),
            ),
        )
    )

    language = normalize_text(row.get("language", "")) or str(default_language).strip()
    speaker_name = normalize_text(row.get("speaker_name", "")) or str(default_speaker_name).strip()
    source_audio = normalize_path(row.get("source_audio", ""), base_dir=manifest_dir)
    asr_source = normalize_text(row.get("asr_source", "")) or str(default_asr_source).strip()
    text_status = normalize_text(row.get("text_status", "")) or str(default_text_status).strip()

    start_sec = safe_float(row.get("start_sec", math.nan))
    end_sec = safe_float(row.get("end_sec", math.nan))
    duration_sec = safe_float(row.get("duration_sec", math.nan))

    metadata = row.get("metadata", {})
    if not isinstance(metadata, dict):
        metadata = {
            "original_metadata_repr": repr(metadata),
        }

    metadata = dict(metadata)
    metadata.update(
        {
            "fewshot_export_source": "export_fewshot_stage2_manifest.py",
            "fewshot_manifest_row_index": int(row_index),
            "fewshot_original_row_keys": sorted(list(row.keys())),
        }
    )

    issues: list[str] = []

    if not wav_path:
        issues.append("missing_wav_path")

    if not text and not bool(allow_empty_text):
        issues.append("empty_text")

    if issues:
        return (
            None,
            {
                "row_index": int(row_index),
                "sample_id": sample_id,
                "wav_path": wav_path,
                "issues": issues,
                "row_preview": {
                    "sample_id": row.get("sample_id"),
                    "wav_path": row.get("wav_path"),
                    "target_wav_path": row.get("target_wav_path"),
                    "text": row.get("text"),
                    "raw_text": row.get("raw_text"),
                    "language": row.get("language"),
                    "speaker_name": row.get("speaker_name"),
                },
            },
        )

    item = ExportItem(
        sample_id=sample_id,
        wav_path=wav_path,
        text=text,
        language=language,
        speaker_name=speaker_name,
        source_audio=source_audio,
        start_sec=start_sec,
        end_sec=end_sec,
        duration_sec=duration_sec,
        asr_source=asr_source,
        text_status=text_status,
        metadata=metadata,
    )

    return (
        item,
        {
            "row_index": int(row_index),
            "sample_id": sample_id,
            "wav_path": wav_path,
            "text_chars": len(text),
            "language": language,
            "speaker_name": speaker_name,
            "duration_sec": (
                float(duration_sec)
                if is_finite_number(duration_sec)
                else None
            ),
            "text_status": text_status,
        },
    )


def manifest_rows_to_export_items(
    rows: list[dict[str, Any]],
    *,
    manifest_dir: Path,
    default_speaker_name: str,
    default_language: str,
    default_asr_source: str,
    default_text_status: str,
    allow_empty_text: bool,
    skip_invalid_rows: bool,
) -> tuple[list[ExportItem], dict[str, Any]]:
    """
    EN:
    Convert manifest rows into ExportItem list.

    ZH:
    将 manifest 行转换为 ExportItem 列表。
    """
    items: list[ExportItem] = []
    converted_rows: list[dict[str, Any]] = []
    invalid_rows: list[dict[str, Any]] = []

    seen_sample_ids: set[str] = set()
    duplicate_sample_ids: list[str] = []

    for row_index, row in enumerate(rows, start=1):
        item, info = row_to_export_item(
            row,
            row_index=row_index,
            manifest_dir=manifest_dir,
            default_speaker_name=default_speaker_name,
            default_language=default_language,
            default_asr_source=default_asr_source,
            default_text_status=default_text_status,
            allow_empty_text=allow_empty_text,
        )

        if item is None:
            invalid_rows.append(info)
            if not bool(skip_invalid_rows):
                raise ValueError(
                    "Invalid manifest row found. "
                    f"row_index={row_index}, info={info}"
                )
            continue

        if item.sample_id in seen_sample_ids:
            duplicate_sample_ids.append(item.sample_id)

        seen_sample_ids.add(item.sample_id)

        items.append(item)
        converted_rows.append(info)

    if duplicate_sample_ids:
        raise ValueError(
            "Duplicate sample_id values found in manifest: "
            f"{sorted(set(duplicate_sample_ids))[:20]}"
        )

    if not items:
        raise ValueError(
            "No valid rows converted to ExportItem. "
            f"invalid_rows={len(invalid_rows)}"
        )

    report = {
        "num_input_rows": int(len(rows)),
        "num_converted_items": int(len(items)),
        "num_invalid_rows": int(len(invalid_rows)),
        "invalid_rows": invalid_rows,
        "converted_rows": converted_rows,
    }

    return items, report


def print_preview(
    *,
    output_stage2_manifest: str | Path,
    prompt_selection_report_path: str | Path,
    conversion_report: dict[str, Any],
    max_preview_records: int,
) -> None:
    """
    EN:
    Print a concise export preview.

    ZH:
    打印简洁导出预览。
    """
    print("====================================================")
    print("Few-shot Stage2 manifest export finished")
    print("====================================================")
    print(f"output_stage2_manifest       : {Path(output_stage2_manifest).resolve()}")
    print(f"prompt_selection_report_path : {Path(prompt_selection_report_path).resolve()}")
    print(f"num_input_rows               : {conversion_report['num_input_rows']}")
    print(f"num_converted_items          : {conversion_report['num_converted_items']}")
    print(f"num_invalid_rows             : {conversion_report['num_invalid_rows']}")

    converted = conversion_report.get("converted_rows", [])
    if converted:
        print("----------------------------------------------------")
        print("Converted row preview:")
        for row in converted[: int(max_preview_records)]:
            print(
                f"  - {row.get('sample_id')} | "
                f"speaker={row.get('speaker_name')} | "
                f"lang={row.get('language')} | "
                f"text_chars={row.get('text_chars')} | "
                f"duration={row.get('duration_sec')}"
            )

    invalid = conversion_report.get("invalid_rows", [])
    if invalid:
        print("----------------------------------------------------")
        print("Invalid row preview:")
        for row in invalid[: int(max_preview_records)]:
            print(f"  - row_index={row.get('row_index')} | issues={row.get('issues')}")

    print("====================================================")


# ============================================================
# Main
# 主入口
# ============================================================
def main() -> None:
    args = parse_args()

    manifest_path = Path(args.manifest_jsonl).resolve()
    output_stage2_manifest = Path(args.output_stage2_manifest).resolve()

    if args.prompt_selection_report_path:
        prompt_selection_report_path = Path(args.prompt_selection_report_path).resolve()
    else:
        prompt_selection_report_path = Path(
            resolve_default_report_path(
                output_stage2_manifest,
                "prompt_selection_report.json",
            )
        ).resolve()

    if args.conversion_report_path:
        conversion_report_path = Path(args.conversion_report_path).resolve()
    else:
        conversion_report_path = Path(
            resolve_default_report_path(
                output_stage2_manifest,
                "fewshot_manifest_conversion_report.json",
            )
        ).resolve()

    rows = read_jsonl(manifest_path)

    items, conversion_report = manifest_rows_to_export_items(
        rows,
        manifest_dir=manifest_path.parent,
        default_speaker_name=args.default_speaker_name,
        default_language=args.default_language,
        default_asr_source=args.default_asr_source,
        default_text_status=args.default_text_status,
        allow_empty_text=bool(args.allow_empty_text),
        skip_invalid_rows=bool(args.skip_invalid_rows),
    )

    output_stage2_manifest.parent.mkdir(parents=True, exist_ok=True)
    prompt_selection_report_path.parent.mkdir(parents=True, exist_ok=True)
    conversion_report_path.parent.mkdir(parents=True, exist_ok=True)

    export_stage2_manifest_jsonl(
        items=items,
        output_path=output_stage2_manifest,
        prompt_mode=args.prompt_mode,
        fixed_prompt_wav_path=args.fixed_prompt_wav_path,
        prompt_selection_report_path=prompt_selection_report_path,
        min_prompt_sec=float(args.min_prompt_sec),
        max_prompt_sec=float(args.max_prompt_sec),
        prefer_prompt_sec=float(args.prefer_prompt_sec),
        allow_self_prompt=bool(args.allow_self_prompt),
        strict_prompt_duration=bool(args.strict_prompt_duration),
    )

    conversion_report.update(
        {
            "manifest_jsonl": str(manifest_path),
            "output_stage2_manifest": str(output_stage2_manifest),
            "prompt_selection_report_path": str(prompt_selection_report_path),
            "prompt_mode": str(args.prompt_mode),
            "fixed_prompt_wav_path": (
                str(Path(args.fixed_prompt_wav_path).resolve())
                if args.fixed_prompt_wav_path
                else None
            ),
            "prompt_policy": {
                "min_prompt_sec": float(args.min_prompt_sec),
                "max_prompt_sec": float(args.max_prompt_sec),
                "prefer_prompt_sec": float(args.prefer_prompt_sec),
                "allow_self_prompt": bool(args.allow_self_prompt),
                "strict_prompt_duration": bool(args.strict_prompt_duration),
            },
            "fallbacks": {
                "default_speaker_name": str(args.default_speaker_name),
                "default_language": str(args.default_language),
                "default_asr_source": str(args.default_asr_source),
                "default_text_status": str(args.default_text_status),
            },
        }
    )

    save_json(conversion_report, conversion_report_path)

    if bool(args.print_records_preview):
        print_preview(
            output_stage2_manifest=output_stage2_manifest,
            prompt_selection_report_path=prompt_selection_report_path,
            conversion_report=conversion_report,
            max_preview_records=int(args.max_preview_records),
        )
    else:
        print(f"[DONE] Saved stage2 manifest -> {output_stage2_manifest}")
        print(f"[DONE] Saved prompt report   -> {prompt_selection_report_path}")
        print(f"[DONE] Saved convert report  -> {conversion_report_path}")


if __name__ == "__main__":
    main()